[package]
name = "backoffice-payment-provider"
authors.workspace = true
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true, features = ["json"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
