// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfigInterface = {
  identifier: number;
  appName: string | null;
  maintenanceMode: boolean;
  supportEmail: string | null;
  createdAt: string;
  lastUpdated: string;
};
