// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplaintStatus } from "./sea_orm_active_enums";

export type ComplaintsInterface = {
  identifier: string;
  customerIdentifier: string;
  orderIdentifier: string | null;
  subject: string;
  description: string;
  status: ComplaintStatus | null;
  createdAt: string;
  updatedAt: string | null;
};
