// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateUploadRequest = {
  file: File;
  name: string;
  file_type: string | null;
  starred: boolean | null;
};
