// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateEmailCommand = {
  subject: string;
  body: string;
  senderEmail: string;
  recipientEmail: string;
  tag: string | null;
  hasAttachments: boolean | null;
  data: JsonValue | null;
};
