// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmailMessage = {
  fromAddress: string;
  fromName: string;
  toAddress: string;
  toName: string;
  subject: string;
  htmlBody: string;
};
