// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationStatus } from "./InvitationStatus";

export type InvitationInterface = {
  identifier: string;
  email: string;
  status: InvitationStatus | null;
  token: string;
  createdAt: string;
  updatedAt: string | null;
};
