// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvoiceStatus } from "./InvoiceStatus";

export type InvoicesInterface = {
  identifier: string;
  customerIdentifier: string;
  orderIdentifier: string;
  invoiceNumber: string;
  amount: bigint;
  status: InvoiceStatus | null;
  dueDate: string;
  createdAt: string;
  updatedAt: string | null;
};
