// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderStatus } from "./OrderStatus";

export type OrdersInterface = {
  identifier: string;
  productIdentifier: string;
  quantity: number;
  status: OrderStatus | null;
  createdAt: string;
  updatedAt: string | null;
};
