// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductsEntity = {
  identifier: string;
  name: string;
  picture: string | null;
  price: string;
  description: string;
  createdByIdentifier: string | null;
  marketplaceIdentifier: string | null;
  createdAt: string;
  updatedAt: string | null;
  currencyIdentifier: string | null;
};
