// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductsInterface = {
  identifier: string;
  name: string;
  picture: string | null;
  price: bigint;
  description: string;
  createdAt: string;
  updatedAt: string | null;
  currencyIdentifier: string | null;
};
