// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTeamMemberCommand = {
  name: string | null;
  phone: string | null;
  role: string | null;
  blocked: boolean | null;
};
