// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from "./FileType";

export type UploadsInterface = {
  identifier: string;
  name: string;
  url: string;
  fileSize: bigint | null;
  starred: boolean;
  createdAt: string;
  updatedAt: string | null;
  fileType: FileType | null;
  filePath: string;
  thumbnailUrl: string;
};
