// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UploadsInterface = {
  identifier: string;
  name: string;
  src: string;
  fileType: string | null;
  size: bigint | null;
  starred: boolean;
  userIdentifier: string | null;
  createdAt: string;
  updatedAt: string | null;
};
