// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type App = { identifier: number, app_name: string | null, maintenance_mode: boolean, support_email: string | null, created_at: string, last_updated: string, };
