// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Email = {
  identifier: string;
  subject: string;
  body: string;
  senderEmail: string;
  recipientEmail: string;
  dateSent: string;
  tag: string | null;
  isRead: boolean;
  isStarred: boolean;
  hasAttachments: boolean;
  data: Record<string, unknown> | null;
  userIdentifier: string | null;
  createdAt: string;
  updatedAt: string | null;
};
