// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrivilegedUser = { email: string | null, identifier: string, first_name: string | null, last_name: string | null, is_active: boolean, role_name: string, role_description: string | null, };
