// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductWithCurrency = { identifier: string, name: string, price: number, description: string, picture: string | null, createdByIdentifier: string | null, marketplaceIdentifier: string | null, createdAt: string, updatedAt: string, currencyCode: string, currency: string, country: string, flag: string | null, currencyIdentifier: string, };
