[package]
name = "backoffice_console"
version = "0.1.0"
edition = "2024"

[lib]
name = "backoffice_console_lib"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "bin/cli.rs"

[[bin]]
name = "ui"
path = "bin/ui.rs"

[dependencies]
axum = { version = "0.8.9", features = ["macros", "tracing"] }
clap = { version = "4.5", features = ["derive"] }
console = "0.15"
convert_case = "0.8"
dialoguer = "0.11"
serde = { version = "1.0.228", features = ["derive"] }
validators = { version = "0.25.3", features = ["serde"] }
tokio = { version = "1", features = ["full", "macros", "rt", "rt-multi-thread"] }
sanitizer = { version = "1.0.0", features = ["derive"] }
tower-http = { version = "0.7.0", features = ["cors", "fs", "limit", "request-id", "sensitive-headers", "timeout"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0.18"
tower = { version = "0.5.3", features = ["util"] }
