//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "app_config")]
#[serde(rename_all = "camelCase")]
#[backoffice_macros::ts_rs_export_sea_orm_entity_name]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub app_name: Option<String>,
    pub maintenance_mode: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub support_email: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub last_updated: DateTimeWithTimeZone,
    pub default_currency: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_language: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub brand_color: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::DefaultCurrency",
        to = "super::countries::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Countries,
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::countries::Entity")]
    Countries,
}
