//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod activities;
pub mod admin_users;
pub mod app_config;
pub mod countries;
pub mod emails;
pub mod invitation;
pub mod newsletter;
pub mod orders;
pub mod prelude;
pub mod products;
pub mod sea_orm_active_enums;
pub mod teams;
pub mod uploads;
pub mod user_roles;
pub mod users;

seaography::register_entity_modules!([
    activities,
    admin_users,
    app_config,
    countries,
    emails,
    invitation,
    newsletter,
    orders,
    products,
    teams,
    uploads,
    user_roles,
    users,
]);
seaography::register_active_enums!([
    sea_orm_active_enums::FileType,
    sea_orm_active_enums::InvitationStatus,
    sea_orm_active_enums::OrderStatus,
]);
