//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ts_rs :: TS,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "file_type")]
#[ts(export)]
pub enum FileType {
    #[sea_orm(string_value = "image")]
    Image,
    #[sea_orm(string_value = "video")]
    Video,
    #[sea_orm(string_value = "audio")]
    Audio,
    #[sea_orm(string_value = "document")]
    Document,
    #[sea_orm(string_value = "others")]
    Others,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ts_rs :: TS,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "invitation_status")]
#[ts(export)]
pub enum InvitationStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ts_rs :: TS,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status")]
#[ts(export)]
pub enum OrderStatus {
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "fulfilled")]
    Fulfilled,
    #[sea_orm(string_value = "pending")]
    Pending,
}
