//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub(crate) mod activities;
pub mod app;
pub mod marketplace;
pub mod privileged_user;
pub(crate) mod products;
pub mod resource;
pub mod user;
pub mod user_role;
