//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    pub role_identifier: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activities::Entity")]
    Activities,
    #[sea_orm(has_many = "super::emails::Entity")]
    Emails,
    #[sea_orm(has_many = "super::marketplaces::Entity")]
    Marketplaces,
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
    #[sea_orm(has_many = "super::uploads::Entity")]
    Uploads,
    #[sea_orm(
        belongs_to = "super::user_roles::Entity",
        from = "Column::RoleIdentifier",
        to = "super::user_roles::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserRoles,
}

impl Related<super::activities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Activities.def()
    }
}

impl Related<super::emails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Emails.def()
    }
}

impl Related<super::marketplaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Marketplaces.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Uploads.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::activities::Entity")]
    Activities,
    #[sea_orm(entity = "super::emails::Entity")]
    Emails,
    #[sea_orm(entity = "super::marketplaces::Entity")]
    Marketplaces,
    #[sea_orm(entity = "super::products::Entity")]
    Products,
    #[sea_orm(entity = "super::uploads::Entity")]
    Uploads,
    #[sea_orm(entity = "super::user_roles::Entity")]
    UserRoles,
}
