//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    pub role_identifier: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "role_identifier",
        to = "identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user_roles: HasOne<super::user_roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
