//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "app_config")]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "app_config.ts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub app_name: Option<String>,
    pub maintenance_mode: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub support_email: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub last_updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
