//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod activities;
pub mod admin_users;
pub mod app_config;
pub mod countries;
pub mod emails;
pub mod marketplaces;
pub mod newsletter;
pub mod sea_orm_active_enums;
pub mod teams;
pub mod uploads;
pub mod user_roles;
pub mod users;
pub mod products;
seaography::register_entity_modules!([
    activities,
    admin_users,
    app_config,
    countries,
    emails,
    marketplaces,
    newsletter,
    teams,
    uploads,
    user_roles,
    products,
    users,
]);
seaography::register_active_enums!([sea_orm_active_enums::FileType,]);
