//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod activities;
pub mod admin_users;
pub mod app_config;
pub mod countries;
pub mod emails;
pub mod marketplaces;
pub mod newsletter;
pub mod prelude;
pub mod products;
pub mod teams;
pub mod uploads;
pub mod user_roles;
pub mod users;
pub mod backoffice_server_migrations;

seaography::register_entity_modules!([
    activities,
    admin_users,
    app_config,
    countries,
    emails,
    marketplaces,
    newsletter,
    products,
    teams,
    uploads,
    user_roles,
    users,
    backoffice_server_migrations,
]);
