//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    pub name: String,
    pub picture: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub price: Decimal,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub created_by_identifier: Option<String>,
    pub marketplace_identifier: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub currency_identifier: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CurrencyIdentifier",
        to = "super::countries::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Countries,
    #[sea_orm(
        belongs_to = "super::marketplaces::Entity",
        from = "Column::MarketplaceIdentifier",
        to = "super::marketplaces::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Marketplaces,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedByIdentifier",
        to = "super::users::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::marketplaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Marketplaces.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::countries::Entity")]
    Countries,
    #[sea_orm(entity = "super::marketplaces::Entity")]
    Marketplaces,
    #[sea_orm(entity = "super::users::Entity")]
    Users,
}
