// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivitiesInterface = {
  identifier: string;
  createdByIdentifier: string | null;
  resource: string;
  action: string;
  createdAt: string;
  updatedAt: string | null;
};
