// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountriesEntity = {
  identifier: string;
  currencyCode: string;
  currency: string;
  country: string;
  flag: string | null;
};
