// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type EmailsInterface = {
  identifier: string;
  subject: string;
  body: string;
  senderEmail: string;
  recipientEmail: string;
  dateSent: string;
  tag: string | null;
  isRead: boolean;
  isStarred: boolean;
  hasAttachments: boolean;
  data: JsonValue | null;
  userIdentifier: string | null;
  createdAt: string;
  updatedAt: string | null;
};
