//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod activities;
pub mod admin;
pub mod admin_users;
pub mod app_config;
pub mod complaints;
pub mod countries;
pub mod customers;
pub mod emails;
pub mod invitation;
pub mod invoices;
pub mod newsletter;
pub mod orders;
pub mod products;
pub mod sea_orm_active_enums;
pub mod sea_orm_permission;
pub mod sea_orm_resource;
pub mod sea_orm_role;
pub mod sea_orm_role_hierarchy;
pub mod sea_orm_role_permission;
pub mod sea_orm_user_override;
pub mod sea_orm_user_role;
pub mod teams;
pub mod uploads;
pub mod user_roles;
pub mod users;

seaography::register_entity_modules!([
    activities,
    admin,
    admin_users,
    app_config,
    complaints,
    countries,
    customers,
    emails,
    invitation,
    invoices,
    newsletter,
    orders,
    products,
    sea_orm_permission,
    sea_orm_resource,
    sea_orm_role,
    sea_orm_role_hierarchy,
    sea_orm_role_permission,
    sea_orm_user_override,
    sea_orm_user_role,
    teams,
    uploads,
    user_roles,
    users,
]);
seaography::register_active_enums!([
    sea_orm_active_enums::ComplaintStatus,
    sea_orm_active_enums::FileType,
    sea_orm_active_enums::InvitationStatus,
    sea_orm_active_enums::InvoiceStatus,
    sea_orm_active_enums::OrderStatus,
]);
