//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::OrderStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
#[serde(rename_all = "camelCase")]
#[backoffice_macros::ts_rs_export_sea_orm_entity_name]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    pub product_identifier: String,
    pub quantity: i32,
    pub status: Option<OrderStatus>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::complaints::Entity")]
    Complaints,
    #[sea_orm(has_many = "super::invoices::Entity")]
    Invoices,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductIdentifier",
        to = "super::products::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
}

impl Related<super::complaints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Complaints.def()
    }
}

impl Related<super::invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoices.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::complaints::Entity")]
    Complaints,
    #[sea_orm(entity = "super::invoices::Entity")]
    Invoices,
    #[sea_orm(entity = "super::products::Entity")]
    Products,
}
