//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sea_orm_permission")]
#[serde(rename_all = "camelCase")]
#[backoffice_macros::ts_rs_export_sea_orm_entity_name]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub action: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sea_orm_role_permission::Entity")]
    SeaOrmRolePermission,
    #[sea_orm(has_many = "super::sea_orm_user_override::Entity")]
    SeaOrmUserOverride,
}

impl Related<super::sea_orm_role_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeaOrmRolePermission.def()
    }
}

impl Related<super::sea_orm_user_override::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeaOrmUserOverride.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::sea_orm_role_permission::Entity")]
    SeaOrmRolePermission,
    #[sea_orm(entity = "super::sea_orm_user_override::Entity")]
    SeaOrmUserOverride,
}
