//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sea_orm_role_hierarchy")]
#[serde(rename_all = "camelCase")]
#[backoffice_macros::ts_rs_export_sea_orm_entity_name]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub super_role_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sea_orm_role::Entity",
        from = "Column::RoleId",
        to = "super::sea_orm_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SeaOrmRole2,
    #[sea_orm(
        belongs_to = "super::sea_orm_role::Entity",
        from = "Column::SuperRoleId",
        to = "super::sea_orm_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SeaOrmRole1,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(
        entity = "super::sea_orm_role::Entity",
        def = "Relation::SeaOrmRole2.def()"
    )]
    SeaOrmRole2,
    #[sea_orm(
        entity = "super::sea_orm_role::Entity",
        def = "Relation::SeaOrmRole1.def()"
    )]
    SeaOrmRole1,
}
