[package]
name = "backoffice-infra"
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "Infrastructure layer: database repositories, JWT, mailer, ImageKit"

[dependencies]
askama.workspace = true
backoffice-config.workspace = true
backoffice-domain = { workspace = true, features = ["http"] }
base64.workspace = true
bcrypt.workspace = true
chrono.workspace = true
jsonwebtoken.workspace = true
lettre = { version = "0.11.22", features = ["ring", "rustls", "rustls-native-certs"] }
log = "0.4.27"
migration.workspace = true
redis.workspace = true
reqwest.workspace = true
rust_decimal.workspace = true
sea-orm.workspace = true
secrecy = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
