// Auto-generated by scripts/ts-export.js — do not edit manually.

import type { Model as ActivitiesModel } from "./activities";
import type { Model as AdminUsersModel } from "./admin_users";
import type { Model as AppConfigModel } from "./app_config";
import type { Model as CountriesModel } from "./countries";
import type { Model as EmailsModel } from "./emails";
import type { Model as MarketplacesModel } from "./marketplaces";
import type { Model as NewsletterModel } from "./newsletter";
import type { Model as ProductsModel } from "./products";
import type { Model as TeamsModel } from "./teams";
import type { Model as UploadsModel } from "./uploads";
import type { Model as UserRolesModel } from "./user_roles";
import type { Model as UsersModel } from "./users";

export interface Activities extends ActivitiesModel {}
export interface AdminUsers extends AdminUsersModel {}
export interface AppConfig extends AppConfigModel {}
export interface Countries extends CountriesModel {}
export interface Emails extends EmailsModel {}
export interface Marketplaces extends MarketplacesModel {}
export interface Newsletter extends NewsletterModel {}
export interface Products extends ProductsModel {}
export interface Teams extends TeamsModel {}
export interface Uploads extends UploadsModel {}
export interface UserRoles extends UserRolesModel {}
export interface Users extends UsersModel {}
