// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamsEntity = {
  identifier: string;
  name: string;
  email: string;
  phone: string | null;
  role: string | null;
  blocked: boolean;
  createdAt: string;
  updatedAt: string | null;
};
