// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsersEntity = {
  identifier: string;
  firstName: string | null;
  lastName: string | null;
  email: string;
  password: string;
  createdAt: string;
  updatedAt: string | null;
  isActive: boolean;
  roleIdentifier: string | null;
};
