#!/usr/bin/env node
/*
1. Rewrites bare #[ts(export)] in SeaORM-generated entity files to
   #[ts(export, export_to = "<stem>.ts")] so ts-rs emits per-file bindings.
2. Runs cargo build to trigger ts-rs codegen, producing one .ts binding per
   entity file in the frontend's bindings directory.
3. Generates index.ts re-exporting all binding types.

TS_RS_BINDINGS_DIR is set by backoffice/backoffice/build.rs.

Usage (from repo root):
    node scripts/ts-export.js [entities_dir]

entities_dir defaults to backoffice/backoffice/src/domain/models.
Bindings are written to backoffice-web/app/bindings/.
*/

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TS_EXPORT_RE = /#\[ts\(export\)\]/;
const ENUM_RE = /^pub enum (\w+)/gm;

const SKIP = new Set(["mod", "prelude"]);

const ENUM_SOURCES = {
  sea_orm_active_enums: path.join("backoffice", "src", "enums.rs"),
};

/** Return sorted enum names found in a Rust source file. */
function discoverEnums(rustSrc) {
  try {
    const text = fs.readFileSync(rustSrc, "utf8");
    const names = [];
    let m;
    while ((m = ENUM_RE.exec(text)) !== null) {
      names.push(m[1]);
    }
    return names.sort();
  } catch {
    return [];
  }
}

function buildSpecial(projectRoot) {
  const special = {};
  for (const [stem, src] of Object.entries(ENUM_SOURCES)) {
    const names = discoverEnums(path.join(projectRoot, src));
    if (names.length > 0) {
      special[stem] = names;
    }
  }
  return special;
}

function toPascal(stem) {
  return stem
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function fixFile(filePath) {
  const stem = path.basename(filePath, ".rs");
  const replacement = `#[ts(export, export_to = "${stem}.ts")]`;
  const original = fs.readFileSync(filePath, "utf8");
  const updated = original.replace(TS_EXPORT_RE, replacement);
  if (updated === original) return false;
  fs.writeFileSync(filePath, updated, "utf8");
  return true;
}

function generateIndex(entitiesDir, special) {
  const header = "// Auto-generated by scripts/ts-export.js — do not edit manually.\n";
  const specialExports = [];
  const imports = [];
  const interfaces = [];

  const files = fs
    .readdirSync(entitiesDir)
    .filter((f) => f.endsWith(".rs"))
    .sort();

  for (const file of files) {
    const stem = path.basename(file, ".rs");
    if (SKIP.has(stem)) continue;

    const bindingPath = `./${stem}`;

    if (special[stem]) {
      const names = special[stem].join(", ");
      specialExports.push(`export type { ${names} } from "${bindingPath}";\n`);
    } else {
      const typeName = toPascal(stem);
      imports.push(`import type { Model as ${typeName}Model } from "${bindingPath}";\n`);
      interfaces.push(`export interface ${typeName} extends ${typeName}Model {}\n`);
    }
  }

  // specialExports.push('export type { JsonValue } from "./serde_json/JsonValue";\n');

  const lines = [header, ...specialExports, "\n", ...imports, "\n", ...interfaces];

  const frontendBindingsDir = bindingsDir(entitiesDir);
  fs.mkdirSync(frontendBindingsDir, { recursive: true });
  const indexPath = path.join(frontendBindingsDir, "index.ts");
  fs.writeFileSync(indexPath, lines.join(""), "utf8");
  console.log(
    `  wrote: ${indexPath} (${imports.length} interfaces, ${specialExports.length} type exports)`
  );
}

function bindingsDir(entitiesDir) {
  return path.resolve(entitiesDir, "../../../../backoffice-web/app/bindings");
}

function updateBindings(entitiesDir, cargoDir) {
  const outDir = bindingsDir(entitiesDir);

  const expectedFiles = fs
    .readdirSync(entitiesDir)
    .filter((f) => f.endsWith(".rs"))
    .map((f) => path.basename(f, ".rs") + ".ts")
    .filter((f) => !SKIP.has(path.basename(f, ".ts")));

  const needsRebuild =
    !fs.existsSync(outDir) ||
    expectedFiles.some((f) => !fs.existsSync(path.join(outDir, f)));

  if (!needsRebuild) return;

  console.log("  triggering ts-rs codegen (cargo build) …");
  fs.mkdirSync(outDir, { recursive: true });

  const entityFiles = fs
    .readdirSync(entitiesDir)
    .filter((f) => f.endsWith(".rs"))
    .map((f) => path.join(entitiesDir, f));

  for (const f of entityFiles) {
    const now = new Date();
    fs.utimesSync(f, now, now);
  }

  execSync("cargo build -p backoffice", {
    cwd: cargoDir,
    stdio: "inherit",
  });
}

function main() {
  const entitiesDir = path.resolve(
    process.argv[2] || "backoffice/src/domain/models"
  );

  if (!fs.existsSync(entitiesDir)) {
    console.error(`error: directory not found: ${entitiesDir}`);
    process.exit(1);
  }

  const projectRoot = path.resolve(entitiesDir, "../../..", "..");
  const special = buildSpecial(projectRoot);

  // for (const [stem, names] of Object.entries(special)) {
  //   console.log(`  enums from ${ENUM_SOURCES[stem]}: ${names.join(", ")}`);
  // }

  const changed = fs
    .readdirSync(entitiesDir)
    .filter((f) => f.endsWith(".rs"))
    .sort()
    .filter((f) => fixFile(path.join(entitiesDir, f)));

  if (changed.length > 0) {
    for (const f of changed) {
      console.log(`  patched: ${f}`);
    }
  } else {
    console.log("  nothing to patch (no bare #[ts(export)] found)");
  }

  const cargoDir = path.resolve(__dirname, "..", "backoffice", "backoffice");
  updateBindings(entitiesDir, cargoDir);

  generateIndex(entitiesDir, special);
}

main();
