// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketPlace = { identifier: string, name: string, slug: string, description: string, userIdentifier: string, createdAt: string, updatedAt: string, };
