// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketplaceWithProducts = { identifier: string, userIdentifier: string | null, createdAt: string, updatedAt: string, name: string, description: string, products: array, };
