// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Product = { identifier: string, name: string, price: number, description: string, picture: string | null, createdByIdentifier: string | null, marketplaceIdentifier: string | null, createdAt: string, updatedAt: string, currencyIdentifier: string | null, };
